#!/bin/sh

RXVT=rxvt-unicode
#RXVT=rxvt

HOST=`cat /etc/hostname` # I don't know why $HOST doesn't exist in the environment of XMonad

case $HOST in
maxwell)
	SIZE=10
;;
*)
	SIZE=12
;;
esac

exec $RXVT -fn "xft:inconsolata:size=$SIZE:hintstyle=hintslight" -bg midnightblue -fg yellow $@
